name: Github CI

on:
  push:
    tags:
      - v**

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Running Build Service Pace
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd pace-app/service-go/
            sudo git pull origin master
            cd ..
            sudo docker compose up -d --build service-go
            sudo docker ps